# Site settings
title: Mårten Björk &mdash; Designer and Developer
email: marten@upperdog.se
description: > # this means to ignore newlines until "baseurl:"
   I'm a web designer and developer. In 2011, I co-founded Upperdog – a small, responsive-minded agency. 
baseurl: "" # the subpath of your site, e.g. /
uploadsurl: "https://s3.amazonaws.com/martenbjork.com/media/"
url: "http://martenbjork.com" # the base hostname & protocol for your site
twitter_username: martenbjork
github_username: martenbjork

# Collections
collections:
    trips:
        output: true
        permalink: /trips/:path/

    reading:
        output: true
        permalink: /reading/:path/

    portfolio:
        output: true
        permalink: /portfolio/:path/

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
gems:
    - jekyll-sitemap
